<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Projeto_integrador2</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="top-view-coffee-tamper-with-copy-space.jpg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.10.07.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.10.53.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.11.21.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.11.57.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.12.11.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="top-view-coffee-tamper-with-copy-space.jpg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.10.07.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.10.53.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.11.21.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.11.57.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.12.11.jpeg" />
  </ItemGroup>

</Project>
