<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Projeto_integrador2</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="b4f3f5aedd8597e83587ea9b1fb00c67.jpg" />
    <None Remove="croissant.jpg" />
    <None Remove="croquete.jpg" />
    <None Remove="empada.jpg" />
    <None Remove="graos cafe.jpg" />
    <None Remove="LOGO CAFE.png" />
    <None Remove="Receita de Risoles E Versões Diferentes Macias Com Massa Mais Que Especial.jpg" />
    <None Remove="sanduiche.jpg" />
    <None Remove="top-view-coffee-tamper-with-copy-space.jpg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.10.07.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.10.53.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.11.21.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.11.57.jpeg" />
    <None Remove="WhatsApp Image 2026-05-26 at 20.12.11.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="b4f3f5aedd8597e83587ea9b1fb00c67.jpg" />
    <Resource Include="croissant.jpg" />
    <Resource Include="croquete.jpg" />
    <Resource Include="empada.jpg" />
    <Resource Include="graos cafe.jpg" />
    <Resource Include="LOGO CAFE.png" />
    <Resource Include="Receita de Risoles E Versões Diferentes Macias Com Massa Mais Que Especial.jpg" />
    <Resource Include="sanduiche.jpg" />
    <Resource Include="top-view-coffee-tamper-with-copy-space.jpg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.10.07.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.10.53.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.11.21.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.11.57.jpeg" />
    <Resource Include="WhatsApp Image 2026-05-26 at 20.12.11.jpeg" />
  </ItemGroup>

</Project>
