<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Projeto_integrador2</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="2.png" />
    <None Remove="agua com gás.png" />
    <None Remove="agua normal.png" />
    <None Remove="bauru-de-forno-5-.avif" />
    <None Remove="BtnVoltarDaTelaEscolher.png" />
    <None Remove="BtnVoltarDaTelaEscolher2.png" />
    <None Remove="ChatGPT Image 11 de jun. de 2026, 20_20_00.png" />
    <None Remove="ChatGPT Image 11 de jun. de 2026, 20_28_20.png" />
    <None Remove="ChatGPT Image 29 de jun. de 2026, 20_00_35.png" />
    <None Remove="ChatGPT Image 6 de jul. de 2026, 20_37_21.png" />
    <None Remove="Cold Brew.jpeg" />
    <None Remove="croissant.jpg" />
    <None Remove="croquete.jpg" />
    <None Remove="DescriçãoDeBebida-Background.png" />
    <None Remove="Design-sem-nome.webp" />
    <None Remove="empada.jpg" />
    <None Remove="enroladinho-de-salsicha-com-catupiry-1.jpg.webp" />
    <None Remove="EscolherBackground.png" />
    <None Remove="Frappuchino.jpeg" />
    <None Remove="iced latte.jpeg" />
    <None Remove="Iced Moccha.jpeg" />
    <None Remove="Image5.png" />
    <None Remove="Image6.png" />
    <None Remove="img %281%29.jpeg" />
    <None Remove="img %281%29.jpg" />
    <None Remove="img %281%29.png" />
    <None Remove="img %282%29.jpeg" />
    <None Remove="img %282%29.jpg" />
    <None Remove="img %283%29.jpeg" />
    <None Remove="img %284%29.jpeg" />
    <None Remove="img %284%29.png" />
    <None Remove="img %285%29.jpeg" />
    <None Remove="img %287%29.png" />
    <None Remove="img %288%29.png" />
    <None Remove="img1.jpg" />
    <None Remove="img3.png" />
    <None Remove="Img\img %284%29.png" />
    <None Remove="Img\img %287%29.png" />
    <None Remove="Img\img %288%29.png" />
    <None Remove="Img\img3.png" />
    <None Remove="Pizza Doce.jpg" />
    <None Remove="pizza.jpg" />
    <None Remove="qz8j4.jpg" />
    <None Remove="PainelBebidas.jpg" />
    <None Remove="sanduiche.jpg" />
    <None Remove="sanduiche.jpeg" />
    <None Remove="bauru.jpeg" />
    <None Remove="FundoCafe.jpg" />
    <None Remove="superficie-escura-com-espaco-em-branco-e-fast-food-menu_23-2147684608.jpg" />
    <None Remove="walpaper de descrição de bebida e lanche.png" />
    <None Remove="sonho-chocolate.jpg" />
    <None Remove="pizza-frango.jpg" />
    <None Remove="pizza-chocolate.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="2.png" />
    <Resource Include="agua com gás.png" />
    <Resource Include="agua normal.png" />
    <Resource Include="bauru-de-forno-5-.avif" />
    <Resource Include="BtnVoltarDaTelaEscolher.png" />
    <Resource Include="BtnVoltarDaTelaEscolher2.png" />
    <Resource Include="ChatGPT Image 29 de jun. de 2026, 20_00_35.png" />
    <Resource Include="ChatGPT Image 6 de jul. de 2026, 20_37_21.png" />
    <Resource Include="Cold Brew.jpeg" />
    <Resource Include="croissant.jpg" />
    <Resource Include="croquete.jpg" />
    <Resource Include="DescriçãoDeBebida-Background.png" />
    <Resource Include="Design-sem-nome.webp" />
    <Resource Include="empada.jpg" />
    <Resource Include="enroladinho-de-salsicha-com-catupiry-1.jpg.webp" />
    <Resource Include="EscolherBackground.png" />
    <Resource Include="Frappuchino.jpeg" />
    <Resource Include="iced latte.jpeg" />
    <Resource Include="Iced Moccha.jpeg" />
    <Resource Include="Image5.png" />
    <Resource Include="Image6.png" />
    <Resource Include="img (1).jpeg" />
    <Resource Include="img (1).jpg" />
    <Resource Include="img (1).png" />
    <Resource Include="img (2).jpeg" />
    <Resource Include="img (2).jpg" />
    <Resource Include="img (3).jpeg" />
    <Resource Include="img (4).jpeg" />
    <Resource Include="img (5).jpeg" />
    <Resource Include="img1.jpg" />
    <Resource Include="Img\ChatGPT Image 11 de jun. de 2026, 20_20_00.png" />
    <Resource Include=".png" />
    <Resource Include="Img\ChatGPT Image 11 de jun. de 2026, 20_28_20.png" />
    <Resource Include="Img\img (4).png" />
    <Resource Include="Img\img (7).png" />
    <Resource Include="Img\img (8).png" />
    <Resource Include="Img\img3.png" />
    <Resource Include="Pizza Doce.jpg" />
    <Resource Include="pizza.jpg" />
    <Resource Include="qz8j4.jpg" />
    <Resource Include="PainelBebidas.jpg" />
    <Resource Include="sanduiche.jpg" />
    <Resource Include="sanduiche.jpeg" />
    <Resource Include="bauru.jpeg" />
    <Resource Include="superficie-escura-com-espaco-em-branco-e-fast-food-menu_23-2147684608.jpg" />
    <Resource Include="walpaper de descrição de bebida e lanche.png" />
    <Resource Include="sonho-chocolate.jpg" />
  </ItemGroup>

</Project>
